pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'HippoX'
   keywords: '动态线程池项目'
   description: '强大的动态线程池，附带监控报警功能'
  # home config
  en-us:
   title: 'HippoX'
   keywords: '动态线程池项目'
   description: '强大的动态线程池，附带监控报警功能'
 community:
  # 社区页配置
  zh-cn:
   title: 'HippoX'
   keywords: '动态线程池项目'
   description: '强大的动态线程池，附带监控报警功能'
  # community page config
  en-us:
   title: 'HippoX'
   keywords: '动态线程池项目'
   description: '强大的动态线程池，附带监控报警功能'
 blog:
  # 博客列表页配置
  zh-cn:
   title: 'HippoX'
   keywords: '动态线程池项目'
   description: '页面内容简介'
  en-us:
   # blog list page config
   title: 'HippoX'
   keywords: '动态线程池项目'
   description: '强大的动态线程池，附带监控报警功能'